### ISSUE TITLE
Unable to play. Is sign in now required?

### ISSUE THREAD

**Issue by champagnecharly** [expectingtofly/LMS_GlobalPlayer_Plugin#26]
I'm new to this plugin. I've tried a couple of stations recently but they won't play. When using their webpage to play, login is required. Could it be that a user has to sign in before using the service or is it just my install?

**Comment by expectingtofly** [comment]
Yes, live radio has not worked for a week or so.  Global changing there streams.  
There is a new release,  update your plugin to 2.5.1  
2.5.0 is available now, but further improvements are in 2.5.1 which will be available from the main repository later today.

**Comment by champagnecharly** [comment]
Thank you for your reply. thats great news. And thank you for building this also!

**Comment by expectingtofly** [comment]
Version 2.5.2 should fix all streaming issues
