### ISSUE TITLE
Live Play jumps backwards and forwards.  Live rewind has issues

### ISSUE THREAD

**Issue by sws78** [expectingtofly/LMS_GlobalPlayer_Plugin#29]
When playing a live stream (LBC) the audio will skip back a few seconds and then replays what you have just heard.  This happens multiple times.  Also it will skip forward a second  so you miss words etc.

When trying the live rewind, which was working previously, the feed begins to play at the beginning for about five seconds and then jumps forward to the current position.

**Comment by sws78** [comment]
I am running 2.5.1.  This was also happening on the previous version

**Comment by expectingtofly** [comment]
Version 2.5.2 should fix all streaming issues
