### ISSUE TITLE
Live playback not working when synchronising multiple players following update

### ISSUE THREAD

**Issue by ratmash** [expectingtofly/LMS_GlobalPlayer_Plugin#30]
I have installed the update to resolve the issue of live playback no longer working, due to Global moving the goalposts. The update does work, provided that I am only using one player at a time. If I try to synchronise multiple players (like I was doing before) the live playback no longer works.

**Comment by expectingtofly** [comment]
Unfortunately there are lots of problems with the new streams.  I'll be doing an update.  For progress please follow the forum : https://forums.slimdevices.com/forum/user-forums/3rd-party-software/111059-announce-global-player-uk-plugin-classic-fm-capital-smooth-heart-lbc-etc/page19#post1704783

**Comment by expectingtofly** [comment]
Version 2.5.2 should fix all streaming issues
