### ISSUE TITLE
reduced number of stations compared to globalplayer.com website and no login/authentication  available in settings. 

### ISSUE THREAD

**Issue by champagnecharly** [expectingtofly/LMS_GlobalPlayer_Plugin#32]
Thanks for providing this plugin.

The list of stations seems rather limited. E.g no classic FM. On the global player website, one needs to login before accessing classic fm. Could the lack of authentication be what reduces the available list?

Update:  And then it appeared in the list...

**Comment by expectingtofly** [comment]
> Thanks for providing this plugin.
> 
> The list of stations seems rather limited. E.g no classic FM. On the global player website, one needs to login before accessing classic fm. Could the lack of authentication be what reduces the available list?
> 
> Update:  And then it appeared in the list...  

The plugin uses the Global API.  So it provides the stations that global make available.   Classic FM appears for me :
![Screenshot_20241016-172638.png](https://github.com/user-attachments/assets/511d5332-4804-4588-8ea4-e14b3751b48a)
